# Generated by Django 4.0.3 on 2022-04-03 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import travel.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, validators=[travel.common.validators.validate_name_chars])),
                ('banner', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Resort Name')),
                ('type', models.CharField(choices=[('Ski Resort', 'Ski Resort'), ('Beach Resort', 'Beach Resort'), ('SPA Resort', 'SPA Resort'), ('Wellness Resort', 'Wellness Resort'), ('Treking Resort', 'Treking Resort')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, validators=[travel.common.validators.validate_name_chars])),
                ('grade', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor'), ('Bad', 'Bad')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.resort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
